version: '3.9'
services:
  frontend:
    build:
      context: ./new_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - INFLUXDB_HOST=influxdb
    depends_on:
      - influxdb

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./homeassistant_config:/config
    restart: unless-stopped
    privileged: true

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    restart: unless-stopped
