version: '3.9'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks:
      - main_net
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=thesis
      - DOCKER_INFLUXDB_INIT_BUCKET=wattwisely
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ZqgqJU0E-puJtMTk6jvhIb2prakV6btQnsw4gxQJGxgcj1xRwtaao62PsQ0lK0FHLPnonYbPTG8iEbe7bXroJA==

  backend:
    build: ./backend
    container_name: backend
    networks:
      - main_net
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=ZqgqJU0E-puJtMTk6jvhIb2prakV6btQnsw4gxQJGxgcj1xRwtaao62PsQ0lK0FHLPnonYbPTG8iEbe7bXroJA==
      - INFLUXDB_ORG=thesis
      - INFLUXDB_BUCKET=wattwisely
    restart: unless-stopped

  frontend:
    build: ./new_frontend
    container_name: frontend
    networks:
      - main_net
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    networks:
      - main_net
    ports:
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - ./homeassistant/config:/config

volumes:
  influxdb_data:
  homeassistant_data:

networks:
  main_net:
    driver: bridge
    attachable: true