# Generated by Django 5.1.4 on 2025-03-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('requirement_kwh', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserChallenge',
        ),
    ]
