# Generated by Django 5.1.4 on 2025-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='requirement_pct',
            field=models.FloatField(blank=True, help_text='Percent reduction target (e.g. 15 for 15%)', null=True),
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='requirement_pct',
            field=models.FloatField(blank=True, help_text='Percent reduction target (e.g. 25 for 25%)', null=True),
        ),
    ]
