# Generated by Django 5.1.4 on 2025-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_weeklychallenge_delete_userchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='points',
            field=models.IntegerField(default=3),
        ),
    ]
