# Generated by Django 5.1.4 on 2025-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_score_challenge_points_weeklychallenge_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
