# Generated by Django 5.1.4 on 2025-03-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_claimed_alter_challenge_points_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
