# Generated by Django 5.1.4 on 2025-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklychallenge',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='weeklychallenge',
            name='week_start',
        ),
        migrations.AddField(
            model_name='weeklychallenge',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
