# Generated by Django 5.1.4 on 2025-03-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.CharField(default='default_badge.png', max_length=255),
        ),
    ]
