# Generated by Django 5.1.4 on 2025-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_badge_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
