# Generated by Django 5.1.4 on 2025-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_badge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='difficulty',
            field=models.CharField(choices=[('padawatt', 'Padawatt'), ('wattknight', 'Watt Knight'), ('wattmaster', 'Watt Master'), ('wattlord', 'Watt Lord')], default='padawatt', max_length=20),
        ),
    ]
