# Generated by Django 5.1.4 on 2025-04-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_badge_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='achievements.badge')),
            ],
        ),
    ]
